CREATE TABLE properties
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                         NOT NULL UNIQUE,
    unit VARCHAR(20)                          NOT NULL,
    PRIMARY KEY (id)
);