CREATE TABLE categories
(
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                         NOT NULL UNIQUE,
    slug      VARCHAR(255)                         NOT NULL UNIQUE,
    parent_id INT DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX idx_category_parent_id ON categories (parent_id);