CREATE TABLE bases
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                         NOT NULL,
    slug VARCHAR(255)                         NOT NULL,
    PRIMARY KEY (id)
);