CREATE TABLE prices
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value      FLOAT                                NOT NULL,
    oldValue   FLOAT DEFAULT NULL,
    product_id INT   DEFAULT NULL,
    base_id    INT   DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_pr_product FOREIGN KEY (product_id) REFERENCES products (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_pr_base FOREIGN KEY (base_id) REFERENCES bases (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX idx_prices_product_base on prices (product_id, base_id);