CREATE TABLE products
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                         NOT NULL UNIQUE,
    slug        VARCHAR(255)                         NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    vendor_code VARCHAR(50)                          NOT NULL,
    category_id INT  DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_p_category_id FOREIGN KEY (category_id) REFERENCES categories (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX idx_products_category_id ON products (category_id);