CREATE TABLE property_values
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value       VARCHAR(255)                         NOT NULL,
    product_id  INT DEFAULT NULL,
    property_id INT DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_pv_product FOREIGN KEY (product_id) REFERENCES products (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_pv_property FOREIGN KEY (property_id) REFERENCES properties (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX idx_pv_product_property on property_values (product_id, property_id);